spring:
  application:
    name: BidBidBid
  datasource:
    url: jdbc:postgresql://localhost:5432/bidbidbid
    username: postgres
    password: Manifest
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always